# -*- coding: utf-8 -*-
"""Resolution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WmL0rbHH9WJFLvoRlmA0siakDooFv4FT
"""

from google.colab import files
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Define a function to upload images
def upload_images():
    # Use the files.upload() function to upload multiple images
    uploaded = files.upload()

    # Create a list to store the image data and resolutions
    images = []

    # Iterate through each image that was uploaded
    for filename, data in uploaded.items():
        # Read in the image using OpenCV
        img = cv2.imdecode(np.frombuffer(data, np.uint8), cv2.IMREAD_COLOR)

        # Get the image resolution
        height, width, channels = img.shape
        resolution = height * width

        # Append the image data and resolution to the images list
        images.append((img, resolution))

    # Sort the images by resolution
    sorted_images = sorted(images, key=lambda x: x[1])

    return sorted_images




# Upload and sort the images
sorted_images = upload_images()

# # Display the sorted images
# display_images(sorted_images)

# Get the largest image
largest_image = sorted_images[-1][0]

# Display the largest image
cv2_imshow(largest_image)