python youtube.py --file="merged_video.mp4"
                       --title="1st automation uploaded video"
                       --description="by closed ai"
                       --keywords="surfing,Santa Cruz"
                       --category="28"
                       --privacyStatus="private"